spring:
  application:
    name: USER-SERVICE

  datasource:
    username: root
    url: jdbc:mysql://localhost:4444/b2b_db
    password : b2bdb

server:
  port: 9090

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone : http://localhost:5678/eureka/