spring:
  application:
    name: product-service

  datasource:
    username: root
    password: b2bdb
    url: jdbc:mysql://localhost:4444/b2b_db

  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

server:
  port: 9091
  servlet:
    context-path: /api/v1

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:5678/eureka/}
  instance:
    hostname: ${EUREKA_HOST:localhost}