spring:
  application:
      name: eureka-server

server:
  port : 5678
  servlet:
    context-path: /api/v1
eureka:
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:5678/eureka/