spring:
  application:
      name: eureka-server

server:
  port : 5678

eureka:
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:5678/eureka/}