spring:
  application:
      name: api-gateway-service

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - name: Path
                  args:
                      pattern: /api/v1/users/**
            - id: product-service
              uri: lb://product-service
              predicates:
                - name: Path
                  args:
                    pattern: /api/v1/products/**
            - id: order-service
              uri: lb://order-service
              predicates:
                - Path= /api/v1/cart-items/**, /api/v1/orders/**
#                  - name: Path
#                    args:
#                      pattern: /api/v1/cart-items
server:
  port: 8080

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:5678/eureka/
  instance:
    hostname: localhost